# Dependabot Configuration
# Configuração para atualizações automáticas de dependências

version: 2
updates:
  # Atualizações de dependências PHP (Composer)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "rogash"
    assignees:
      - "rogash"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "php"
      - "composer"
    # Atualizações de segurança sempre
    security-updates-only: false
    # Agrupar atualizações relacionadas
    groups:
      phpstan:
        patterns:
          - "phpstan/*"
          - "larastan/*"
      psalm:
        patterns:
          - "psalm/*"
          - "vimeo/psalm"
      quality-tools:
        patterns:
          - "friendsofphp/*"
          - "squizlabs/*"
          - "phpcompatibility/*"
      testing:
        patterns:
          - "phpunit/*"
          - "nunomaduro/*"
          - "laravel/dusk"
      laravel:
        patterns:
          - "laravel/*"
          - "illuminate/*"

  # Atualizações de dependências Node.js (se houver)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    reviewers:
      - "rogash"
    assignees:
      - "rogash"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "node"
      - "npm"
    # Atualizações de segurança sempre
    security-updates-only: false

  # Atualizações de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    reviewers:
      - "rogash"
    assignees:
      - "rogash"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    # Atualizações de segurança sempre
    security-updates-only: false

  # Atualizações de Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "1"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 2
    reviewers:
      - "rogash"
    assignees:
      - "rogash"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    # Atualizações de segurança sempre
    security-updates-only: false
