name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest



    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP 8.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, pdo_sqlite, gd, curl, zip, bcmath, soap, redis, memcached
        tools: composer:v2
        coverage: xdebug

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Install NPM dependencies
      run: npm ci

    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse --memory-limit=2G

    - name: Run Psalm
      run: ./vendor/bin/psalm --no-progress

    

    - name: Run PHP CS Fixer
      run: ./vendor/bin/php-cs-fixer fix --dry-run --diff

    - name: Run PHP_CodeSniffer
      run: ./vendor/bin/phpcs --standard=PSR12 app config database routes tests || true

    - name: Build assets
      run: npm run build

  security:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP 8.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        tools: composer:v2

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Run security audit
      run: composer audit

    - name: Run PHP Security Checker
      run: |
        curl -sSfL https://github.com/fabpot/local-php-security-checker/releases/latest/download/local-php-security-checker_linux_amd64 -o security-checker
        chmod +x security-checker
        ./security-checker composer.lock

  deploy:
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to production
      run: echo "Deploy to production would happen here"
      # Add your deployment logic here
